### ISSUE TITLE
Remove Fedora support 

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/flux-cluster-template#772]
Originally I thought running a distro with a more recent kernel was a good thing. However after running an upgrade my Fedora kernel was updated and it completely hosed rook-ceph on my nodes and had to start over. I got bit by having a pretty much rolling release and it was not fun to have break on me.

I'd really like to keep support for only Ubuntu (maybe Debian) to keep things simple in support and code since these support LTS releases.

To anyone on Fedora Server currently, the code will be removed but there is no problem with you continuing to use it if you are comfortable with managing the Ansible bits yourself.

**Comment by rkoosaar** [comment]
I tried using Fedora Server also, but I find it too unstable. I would say if you want to keep that (Fedora platform) then maybe instead of Fedora use Rocky Linux or Alma Linux as they are based on RHEL, after RH killed CentOS.

If you are between Ubuntu / Debian, then I personally prefer Debian over Ubuntu, I just find debian stable and clean. I feel like Ubuntu tries to add too many things even to their clean image.
